version: '3.7'
services:
  database:
    image: postgres
    container_name: database_finapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=finapi
      - POSTGRES_PASSWORD=finapi
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
